Update LAPS-Stylee

diff --git a/LAPS-Stylee b/LAPS-Stylee
--- a/LAPS-Stylee
+++ b/LAPS-Stylee
@@ -81,8 +81,6 @@ newPass=$(openssl rand -base64 10 | tr -d OoIi1lLS | head -c12;echo)
 ParameterCheck(){
 #
 /bin/echo "Checking parameters."
-#
-#
 # Outputting a Blank Line for Reporting Purposes
 /bin/echo
 #
@@ -147,16 +145,16 @@ fi
 #
 CheckUser (){
 #
-echo Checking If User $resetUser Exists Locally
+/bin/echo Checking If User $resetUser Exists Locally
 #
 # Verify resetUser is a local user on the computer
 checkUser=`dseditgroup -o checkmember -m $resetUser localaccounts | awk '{ print $1 }'`
 #
 if [[ "$checkUser" = "yes" ]]
 	then
-	    echo "$resetUser is a local user on the Computer"
+	    /bin/echo "$resetUser is a local user on the Computer"
 	else
-	    echo "Error: $checkUser is not a local user on the Computer!"
+	    /bin/echo "Error: $checkUser is not a local user on the Computer!"
         ScriptEnd
 	    exit 1
 fi
@@ -169,7 +167,7 @@ fi
 #
 CheckOldPassword (){
 #
-echo Grabbing Current Password From JAMF API
+/bin/echo Grabbing Current Password From JAMF API
 #
 xmlString="<?xml version=\"1.0\" encoding=\"UTF-8\"?><computer><extension_attributes><extension_attribute><name>$ExtensionAttributeName</name><value>$newPass</value></extension_attribute></extension_attributes></computer>"
 #
@@ -177,26 +175,26 @@ oldPass=$(curl -s -f -u $apiUser:$apiPass -H "Accept: application/xml" $apiURL/J
 #
 if [ "$oldPass" == "" ]
 	then
-	    echo "No Password is stored in LAPS."
+	    /bin/echo "No Password is stored in LAPS."
 	else
-	    echo "A Password was found in LAPS."
+	    /bin/echo "A Password was found in LAPS."
 fi
 #
 if [ "$oldPass" != "" ]
 	then
 		passwdA=`dscl /Local/Default -authonly $resetUser $oldPass`
 		#
-        if [ "$passwdA" == "" ]
+		if [ "$passwdA" == "" ]
 			then
-				echo Current Password for User $resetUser is $oldPass
-			    echo "Password stored in LAPS is correct for $resetUser."
+				/bin/echo Current Password for User $resetUser is $oldPass
+				/bin/echo "Password stored in LAPS is correct for $resetUser."
 			else
-			    echo "Error: Password stored in LAPS is not valid for $resetUser."
-				echo Current Password for User $resetUser is $oldPass
-			    oldPass=""
+				/bin/echo "Error: Password stored in LAPS is not valid for $resetUser."
+				/bin/echo Current Password for User $resetUser is $oldPass
+				oldPass=""
 		fi
 	else
-    	oldpass=$oldpass
+		oldpass=$oldpass
 fi
 }
 #
@@ -208,43 +206,41 @@ RunLAPS (){
 #
 if [ "$adminUser" == "JAMF" ]
 	then
-	    echo "JAMF Management Account being used for this process"
-        echo "JAMF Password needs to be Reset to a Known Value."
-        echo 
-        sudo $jamf_binary policy -trigger JAMF-NonComplex
-        #
+		/bin/echo "JAMF Management Account being used for this process"
+		/bin/echo "JAMF Password needs to be Reset to a Known Value."
+		/bin/echo
+		sudo $jamf_binary policy -trigger JAMF-NonComplex
+		#
 		SectionEnd
 fi
 #
 if [ "$oldPass" == "" ]
 	then
-		echo "Current password not available, proceeding with forced update."
-	    $jamf_binary resetPassword -username $resetUser -password $newPass
-	else 
-		echo "Updating password for $resetUser."
-	    $jamf_binary resetPassword -updateLoginKeychain -username $resetUser -oldPassword $oldPass -password $newPass
-
+		/bin/echo "Current password not available, proceeding with forced update."
+		$jamf_binary resetPassword -username $resetUser -password $newPass
+	else
+		/bin/echo "Updating password for $resetUser."
+		$jamf_binary resetPassword -updateLoginKeychain -username $resetUser -oldPassword $oldPass -password $newPass
 fi
 #
-echo "New Password for User $resetUser will be $newPass"
+/bin/echo "New Password for User $resetUser will be $newPass"
 #
 # Outputs User Whose Keychains We Are Going To Delete
-echo Deleting Keychains for user $resetUser
+/bin/echo Deleting Keychains for user $resetUser
 #
 rm -f -r /Users/$resetUser/Library/Keychains
 #
-#
 if [ "$FVstatus" == "FileVault is Off." ]
 	then
-    	echo Not going to set it again as FileVault is DISABLED.
+		/bin/echo Not going to set it again as FileVault is DISABLED.
 	else
 		#
-        if [ "$(fdesetup list | grep -ic "^${resetUser},")" -eq '0' ]
+		if [ "$(fdesetup list | grep -ic "^${resetUser},")" -eq '0' ]
 			then
-				echo User $resetUser is not FileVault Enabled
+				/bin/echo User $resetUser is not FileVault Enabled
 				UserFDE=NO
-			else    
-				echo User $resetUser is FileVault Enabled
+			else
+				/bin/echo User $resetUser is FileVault Enabled
 				UserFDE=YES
 		fi
 		#
@@ -252,28 +248,27 @@ if [ "$FVstatus" == "FileVault is Off." ]
 			then
 				os_ver=$(sw_vers -productVersion)
 				IFS='.' read -r -a ver <<< "$os_ver"
-				echo OS Version = $os_ver
+				/bin/echo OS Version = $os_ver
 				if [[ "${ver[1]}" -ge 13 ]]
 					then
 						# Set it again as the user to update FileVault.
-						echo "Setting Password again as the user to update FileVault (High Sierra or Higher)."
+						/bin/echo "Setting Password again as the user to update FileVault (High Sierra or Higher)."
 						#
-						echo Changing password again to ensure updating filevault and Secure Token
+						/bin/echo Changing password again to ensure updating filevault and Secure Token
 						#
 						sysadminctl -adminUser ${adminUser} -adminPassword ${adminPass} -resetPasswordFor ${resetUser} -newPassword $newPass 
 						#
 					elif [[ "${ver[1]}" -lt 13 ]]
 						then
 							# Set it again as the user to update FileVault.
-							echo "Setting Password again as the user to update FileVault (Pre High Sierra)."
+							/bin/echo "Setting Password again as the user to update FileVault (Pre High Sierra)."
 							sudo -iu ${resetUser} dscl . passwd "/Users/${resetUser}" $newPass $newPass
 				fi
 				#
 			else    
 				# Not going to set it again as the user as account is not Enabled for FileVault.
-				echo Not going to set it again as the user as account is not Enabled for FileVault.
+				/bin/echo Not going to set it again as the user as account is not Enabled for FileVault.
 		fi
-		#
 fi
 }
 #
@@ -283,39 +278,38 @@ fi
 #
 CheckNewPassword (){
 #
-echo "Verifying new password for $resetUser."
+/bin/echo "Verifying new password for $resetUser."
 #
 passwdB=`dscl /Local/Default -authonly $resetUser $newPass`
 #
 if [ "$passwdB" == "" ]
 	then
-	    echo "New password for $resetUser is verified."
+		/bin/echo "New password for $resetUser is verified."
 	else
-	    echo "Error: Password reset for $resetUser was not successful!"
-		echo        
-        #
-        if [ "$adminUser" == "JAMF" ]
+		/bin/echo "Error: Password reset for $resetUser was not successful!"
+		/bin/echo
+		#
+		if [ "$adminUser" == "JAMF" ]
 			then
-			    echo "JAMF Management Account was used for this process"
-		        echo "JAMF Password needs to be Reset to an unknown Complex Value."
-		        echo 
-		        sudo $jamf_binary policy -trigger JAMF-Complex
+				/bin/echo "JAMF Management Account was used for this process"
+				/bin/echo "JAMF Password needs to be Reset to an unknown Complex Value."
+				/bin/echo
+				sudo $jamf_binary policy -trigger JAMF-Complex
 		fi
-        echo
+	/bin/echo
         #        
         ScriptEnd
-	    exit 1
+	exit 1
 fi
 }
 #
 ###############################################################################################################################################
 #
-#
 # Update the LAPS Extention Attribute
 #
 UpdateAPI (){
 #
-echo "Recording new password for $resetUser into LAPS."
+/bin/echo "Recording new password for $resetUser into LAPS."
 #
 /usr/bin/curl -s -u ${apiUser}:${apiPass} -X PUT -H "Content-Type: text/xml" -d "${xmlString}" "${apiURL}/JSSResource/computers/udid/$udid"
 #
@@ -324,18 +318,18 @@ sleep 5
 LAPSpass=$(curl -s -f -u $apiUser:$apiPass -H "Accept: application/xml" $apiURL/JSSResource/computers/udid/$udid/subset/extension_attributes | xpath "//extension_attribute[name=$extAttName]" 2>&1 | awk -F'<value>|</value>' '{print $2}')
 #
 # Outputting a Blank Line for Reporting Purposes
-echo
+/bin/echo
 #
-echo "Verifying LAPS password for $resetUser."
+/bin/echo "Verifying LAPS password for $resetUser."
 passwdC=`dscl /Local/Default -authonly $resetUser $LAPSpass`
 #
 if [ "$passwdC" == "" ]
 	then
-	    echo "LAPS password for $resetUser is verified."
+		/bin/echo "LAPS password for $resetUser is verified."
 	else
-	    echo "Error: LAPS password for $resetUser is not correct!"
-        ScriptEnd
-        exit 1
+		/bin/echo "Error: LAPS password for $resetUser is not correct!"
+		ScriptEnd
+		exit 1
 fi
 }
 #
@@ -389,7 +383,7 @@ ScriptEnd(){
 ###############################################################################################################################################
 #
 # Outputting a Blank Line for Reporting Purposes
-echo
+/bin/echo
 #
 ParameterCheck
 SectionEnd
@@ -399,8 +393,6 @@ SectionEnd
 #
 CheckOldPassword
 SectionEnd
-#
-
 #
 RunLAPS
 SectionEnd
@@ -413,12 +405,12 @@ SectionEnd
 #
 if [ "$adminUser" == "JAMF" ]
 	then
-		echo "JAMF Management Account was used for this process"
-		echo "JAMF Password needs to be Reset to an unknown Complex Value."
-		echo 
+		/bin/echo "JAMF Management Account was used for this process"
+		/bin/echo "JAMF Password needs to be Reset to an unknown Complex Value."
+		/bin/echo
 		sudo $jamf_binary policy -trigger JAMF-Complex
-        #
-        SectionEnd
+		#
+		SectionEnd
 fi
 #
 ScriptEnd
